fans:
  - id: cpu
    hwmon:
      platform: nct6798-isa-02a0
      rpmChannel: 2
      pwmChannel: 2
    neverStop: true
    curve: cpu_curve
  - id: gpu_1
    hwmon:
      platform: nct6798-isa-02a0
      rpmChannel: 1
      pwmChannel: 1
    neverStop: true
    curve: gpu_curve
  - id: gpu_2
    hwmon:
      platform: nct6798-isa-02a0
      rpmChannel: 7
      pwmChannel: 7
    neverStop: true
    curve: gpu_curve

sensors:
  - id: cpu_package
    hwmon:
      platform: coretemp-isa-0000
      index: 1
  - id: gpu_junction
    hwmon:
      platform: amdgpu-pci-0300
      index: 2
       
curves:
  - id: cpu_curve
    linear:
      sensor: cpu_package
      min: 40
      max: 80
  - id: gpu_curve
    linear:
      sensor: gpu_junction
      min: 40
      max: 90

statistics:
  enabled: true
  port: 9000

api:
  enabled: true